name: educode
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.2.1
  cupertino_icons: ^1.0.8
  audioplayers: ^6.0.0
  path_provider: ^2.1.2
  path: ^1.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.14
  bezier_level_map: ^0.0.2
  url_launcher: 6.1.14
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sounds/bg_music.mp3
    - assets/sounds/level_1&2.mp3
    - assets/sounds/level_3&4.mp3
    - assets/sounds/benar.mp3
    - assets/sounds/salah.mp3

    - assets/images/mortarboard.png
    
    - assets/lottie/cat.json
    - assets/lottie/benar.json
    - assets/images/logo.png
    - assets/svg/map_vertical.svg

    - assets/images/current.png
    - assets/images/completed.png
    - assets/images/locked.png

    - assets/images/snake.png
    - assets/images/zebra.png
    - assets/images/cat.png
    - assets/images/fish.png
    - assets/images/monkey.png
    - assets/images/koala.png
    - assets/images/semut.png
    - assets/images/siput.png

    - assets/images/back_icon.png
    - assets/images/volume.png

    - assets/images/car_blue.png
    - assets/images/car_red.png
    - assets/images/car_purple.png
    - assets/images/car_pink.png
    - assets/images/car_orange.png
    - assets/images/car_green.png
    - assets/images/backspace.png

    - assets/images/ball1.png
    - assets/images/ball2.png
    - assets/images/ball3.png
    - assets/images/ball4.png
    - assets/images/ball5.png
    - assets/images/ball6.png

    - assets/images/apple.png
    - assets/images/cherry.png
    - assets/images/orange.png
    - assets/images/grape.png
    - assets/images/mango.png
    - assets/images/banana.png
    - assets/images/watermelon.png
    - assets/images/pear.png
    - assets/images/strawberry.png
    - assets/images/seledri.png
    - assets/images/es_krim.png
    - assets/images/buah.png
    - assets/images/kiwi.png
    - assets/images/pineapple.png

    - assets/images/spinach.png
    - assets/images/broccoli.png
    - assets/images/cauliflower.png

    - assets/images/pohon.jpg
    - assets/images/buaya.jpg
    - assets/images/orang.jpg
    - assets/images/rumah.jpg
    - assets/images/singa.jpg
    - assets/images/cat2.png

    - assets/images/jalan_a.jpg
    - assets/images/jalan_b.jpg
    - assets/images/jalan_c.jpg
    - assets/images/jalan_d.jpg
    - assets/images/jalan_e.jpg
    - assets/images/jalan_f.jpg

    - assets/images/12/anjing.jpg
    - assets/images/12/ayam.jpg
    - assets/images/12/badak.jpg
    - assets/images/12/buaya.jpg
    - assets/images/12/burung.jpg
    - assets/images/12/domba.jpg
    - assets/images/12/gajah.jpg
    - assets/images/12/harimau.jpg
    - assets/images/12/ikan.jpg
    - assets/images/12/jerapah.jpg
    - assets/images/12/kambing.jpg
    - assets/images/12/kancil.jpg
    - assets/images/12/koala.jpg
    - assets/images/12/kucing.jpg
    - assets/images/12/kuda_nil.jpg
    - assets/images/12/kuda.jpg
    - assets/images/12/monyet.jpg
    - assets/images/12/sapi.jpg
    - assets/images/12/singa.jpg
    - assets/images/12/tupai.jpg
    - assets/images/12/ubur_ubur.jpg
    - assets/images/12/ular.jpg
    - assets/images/12/unta.jpg
    - assets/images/12/zebra.jpg

    - assets/images/13/pohon.jpg
    - assets/images/13/jerapah.jpg
    - assets/images/13/gajah.jpg
    - assets/images/13/kudanil.jpg
    - assets/images/13/rusa.jpg
    - assets/images/13/ular.jpg

    - assets/images/panah_kiri_m.png
    - assets/images/panah_bawah_m.png
    - assets/images/panah_kanan_b.png
    - assets/images/panah_kanan_u.png
    - assets/images/panah_atas_u.png
    - assets/images/panah_atas_h.png
    - assets/images/panah_kanan_h.png
    - assets/images/panah_kanan_o.png
    - assets/images/panah_bawah_o.png
    - assets/images/panah_kiri_p.png
    - assets/images/panah_atas_p.png

    - assets/images/panah_kanan.png
    - assets/images/panah_kiri.png
    - assets/images/panah_atas.png
    - assets/images/panah_bawah.png
    - assets/images/run.png

    - assets/images/6/12a1.png
    - assets/images/6/12a2.png
    - assets/images/6/12a3.png
    - assets/images/6/12a4.png
    - assets/images/6/12a5.png

    - assets/images/6/12b1.png
    - assets/images/6/12b2.png
    - assets/images/6/12b3.png
    - assets/images/6/12b4.png
    - assets/images/6/12b5.png

    - assets/images/7/7_1.png
    - assets/images/7/7_2.png
    - assets/images/7/7_3.png

    - assets/images/9/bola1.png
    - assets/images/9/bola2.png
    - assets/images/9/bola3.png
    - assets/images/9/bola4.png

    - assets/images/15/15a.png
    - assets/images/15/15b.png
    - assets/images/15/15c.png

    - assets/images/arrow.png
    - assets/images/contoh_rumah.png
    - assets/images/gambar_a.png
    - assets/images/gambar_a1.jpg
    - assets/images/gambar_b.png
    - assets/images/cross.png
    - assets/images/check.png

    - assets/images/36/1.png
    - assets/images/36/2.png
    - assets/images/36/3.png
    - assets/images/36/4.png
    - assets/images/36/5.png

    - assets/images/18/18.png

    - assets/images/20/1.png
    - assets/images/20/2.png
    - assets/images/20/3.png

    - assets/images/21/a1.png
    - assets/images/21/a2.png
    - assets/images/21/a3.png
    - assets/images/21/b1.png
    - assets/images/21/b2.png
    - assets/images/21/b3.png
    - assets/images/21/c1.png
    - assets/images/21/c2.png
    - assets/images/21/c3.png

    - assets/images/23/semut.png
    - assets/images/23/tikus.png
    - assets/images/23/kucing.png
    - assets/images/23/kambing.png
    - assets/images/23/sapi.png
    - assets/images/23/gajah.png

    - assets/images/24/a1.png
    - assets/images/24/a2.png
    - assets/images/24/b1.png
    - assets/images/24/b2.png

    - assets/images/26/makan.png
    - assets/images/26/badan_bugar.png
    - assets/images/26/ngantuk.png
    - assets/images/26/lapar.png
    - assets/images/26/kenyang.png
    - assets/images/26/tidur.png
    - assets/images/26/sikat_gigi.png
    - assets/images/26/gigi_sehat.png
    - assets/images/26/gigi_sakit.png

    - assets/images/28/a1.png
    - assets/images/28/a2.png
    - assets/images/28/a3.png
    - assets/images/28/a4.png
    - assets/images/28/b1.png
    - assets/images/28/b2.png
    - assets/images/28/b3.png
    - assets/images/28/b4.png
    - assets/images/29/capek.png
    - assets/images/29/gatal.png
    - assets/images/29/haus.png
    - assets/images/29/lapar.png
    - assets/images/29/tidak_tahu.png
    - assets/images/29/ngantuk.png
    - assets/images/29/sakit.png
    - assets/images/29/kotor.png

    - assets/images/30/cucian_basah.png
    - assets/images/30/lapar.png
    - assets/images/30/haus.png
    - assets/images/30/kotor.png
    - assets/images/30/nilai_ujian_jelek.png
    - assets/images/30/tidur.png
    - assets/images/30/kesandung.png
    - assets/images/30/ngantuk.png
    - assets/images/30/gatal.png
    - assets/images/31/orang.jpg
    - assets/images/31/rumah.jpg
    - assets/images/31/gajah.png
    - assets/images/31/jalan_a.png
    - assets/images/31/jalan_d.png
    - assets/images/31/jalan_e.png
    - assets/images/31/jalan_b.png
    - assets/images/31/jalan_c.png
    - assets/images/31/pohon.jpg

    - assets/images/34/burger.png
    - assets/images/34/potongan1.png
    - assets/images/34/potongan2.png
    - assets/images/34/potongan3.png
    - assets/images/34/potongan4.png
    - assets/images/34/potongan5.png
    - assets/images/34/potongan6.png
    - assets/images/40/sayur1.png
    - assets/images/40/sayur2.png
    - assets/images/40/sayur3.png
    - assets/images/40/buah1.png
    - assets/images/40/buah2.png
    - assets/images/40/buah3.png
    - assets/images/40/bola1.png
    - assets/images/40/bola2.png
    - assets/images/40/bola3.png
    
    - assets/images/icons/certificate.svg
    - assets/images/icons/home.svg
    - assets/images/icons/progress.svg
    - assets/images/icons/account.svg

    - assets/images/bg_org.png
    - assets/images/bg_green.png
    - assets/images/bg_blue.png
    - assets/images/ic_books.png
    - assets/images/ic_game.png

    - assets/images/book.png
    - assets/images/winning.png

    - assets/images/exit.svg
    - assets/images/service.svg

    - assets/images/ic_wa.png
    - assets/images/pp.jpg
    - assets/images/sertifikat.jpg

    - assets/lottie/hand_tap.json
    - assets/images/cursor.png
    - assets/images/gambar_org.png
    
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: fredoka
      fonts:
      - asset: fonts/fredoka/Fredoka-Medium.ttf
      # - asset: fonts/fredoka/Fredoka-Italic.ttf
      #   style: italic
    - family: arimo
      fonts:
      - asset: fonts/arimo/Arimo-Medium.ttf
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
    - family: howdybun
      fonts:
      - asset: fonts/howdybun/Howdybun.ttf
    - family: merry-bright
      fonts:
      - asset: fonts/merry-bright/Merry Bright.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
